### ISSUE TITLE
Tortuga

### ISSUE THREAD

**Issue by taracw** [taracw/taraproj#9]
### Engineering Ready
- [x] Match
- [x] [Emphasize FB Sign up](https://github.com/boatbound/galactica/issues/2903)
- [x] [Share itinerary with friends](https://github.com/boatbound/galactica/issues/2886)
- [x] [Targeted renter emails](https://github.com/boatbound/galactica/issues/2892) (non transactional)
- [x] [Stop refunding service fees](https://github.com/boatbound/galactica/issues/2906)
- [x] [Add activities to boats](https://github.com/boatbound/galactica/issues/2890)
- [x] [Boater resume and verification additions](https://github.com/boatbound/galactica/issues/2888)
- [x] [Ability to set weekend and holiday pricing easily](https://github.com/boatbound/galactica/issues/2902)
- [x] [Search Backdoor](https://github.com/boatbound/galactica/issues/2904)

---
### Designer Ready
- [x] [Pro-rated late fees for bookings that are late](https://github.com/boatbound/galactica/issues/2889)
- [x] [Instant Book](https://github.com/boatbound/galactica/issues/2887)
- [x] [Review Improvements](https://github.com/boatbound/galactica/issues/2900)
- [x] [Referral program upgrades](https://github.com/boatbound/galactica/issues/2852)
- [x] [Allow Support Admins to Approve Cancellations](https://github.com/boatbound/galactica/issues/2896)

**Comment by taracw** [comment]
@cjcipriano

**Comment by taracw** [comment]
@jdsling
